apiVersion: v1
kind: Namespace
metadata:
  name: warp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp-url
  labels:
    k8s-app: warp-url
  namespace: warp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: warp-url
  template:
    metadata:
      labels:
        k8s-app: warp-url
    spec:
      containers:
        - name: warp-url
          image: jeevanshu/warp-url
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              name: grpc
            - containerPort: 8443
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: warp-url
  namespace: warp-ns
  labels:
    k8s-app: warp-url
spec:
  sessionAffinity: None
  ports:
  - name: grpc
    port: 8088
    targetPort: grpc
    protocol: TCP
  - name: http-admin
    port: 8443
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: warp-url
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: warp-url-cm
  namespace: warp-ns
data:
  GRPC_PORT: "8088"
  HTTP_PORT: "8443"
  REDIS_URL: "0.0.0.0:6379"
